# Generated by Django 4.2 on 2023-05-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_auto_20181019_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='ktype',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ktype',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
