# Generated by Django 4.2 on 2023-05-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_menuitem_ktype_orderitem_ktype'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='photo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='photo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
