# Generated by Django 4.2 on 2023-05-02 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_menuitem_photo_orderitem_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='photo',
        ),
    ]
